apiVersion: v1
kind: Service
metadata:
  labels:
    app: appuio-acm-example
  name: appuio-acm-example
spec:
  type: NodePort
  selector:
    app: appuio-acm-example
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
